---
_extends: .github

repository:
  name: hs-msgpack-rpc-conduit
  description: A MessagePack RPC implementation in Haskell
  topics: msgpack, rpc, protocol, network
  has_issues: true

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - cirrus-ci
          - Codacy Static Code Analysis
          - code-review/reviewable
